name: Trigger Scrape Function

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'

jobs:
  trigger_scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Curl request
      run: |
        response=$(curl -s -w "\n%{http_code}" https://used-car-scraper-vercel.vercel.app/api/scrape)
        status_code=$(echo "$response" | tail -n1)
        body=$(echo "$response" | sed '$d')
        echo "Status code: $status_code"
        echo -e "Response body:\n$body"
        if [ $status_code -eq 200 ]; then
          echo "Scrape function executed successfully"
        else
          echo "Scrape function failed with status code: $status_code"
          echo -e "Error details:\n$body"
          exit 1
        fi